import { TrekBooking } from "@/types/trek"

export const bookings: TrekBooking[] = [
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
  {
    id: "1",
    customerName: "Ankit Kumar",
    trekName: "Himalayan Base Camp",
    startDate: "2026-02-05",
    endDate: "2026-02-10",
    status: "active",
    peopleCount: 3,
  },
  {
    id: "2",
    customerName: "Ravi Singh",
    trekName: "Kedarkantha Trek",
    startDate: "2026-01-15",
    endDate: "2026-01-20",
    status: "completed",
    peopleCount: 2,
  },
  {
    id: "3",
    customerName: "Priya Sharma",
    trekName: "Valley of Flowers",
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    status: "active",
    peopleCount: 4,
  },
]
